import "./globals.css";
import Navbar from "@/app/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body>
        {/* <div className="container mx-auto px-4"> */}
        <div class="max-w-7xl mx-auto px-4">
          <Navbar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
